name:                publish
version:             0.1.0.0
github:              "githubuser/publish"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/publish#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src
    dependencies:
    - amazonka
    - amazonka-s3
    - bytestring
    - configurator
    - directory
    - filepath
    - lens
    - resourcet
    - text
    - unordered-containers


executables:
    publish:
        main:                Main.hs
        source-dirs:         app
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        dependencies:
        - publish
